name: (Pre-Release) Build YTLitePlusEXTRA IPA
on:
  workflow_dispatch:
    inputs:
      ytlite_version:
        description: "YTLite Version"
        default: "5.2b4"
        required: true
        type: string
        
      display_name:
        description: "App Name"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "BundleID"
        default: "com.google.ios.youtube"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTLitePlusEXTRA IPA (For iPhone 7 Plus)
    runs-on: macos-latest
    permissions:
      contents: write
    ## Force Node.js 24 (Temporary fix for the Github Releases Node.js 20 deprecated errors)
    # env:
    #   ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Download and Validate IPA
        run: wget "https://archive.org/download/com.google.ios.youtube-20.21.6-Decrypted/com.google.ios.youtube-20.21.6-Decrypted.ipa" --no-verbose -O youtube.ipa

      - name: Install Dependencies
        run: brew install make ldid swiftlint

      - name: Set PATH Environment Variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Clone Theos
        run: git clone --quiet --depth=1 --recurse-submodules https://github.com/theos/theos.git
        
      - name: Download iOS SDK
        run: |
          git clone --quiet --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Install cyan and tbd
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          wget --no-verbose "https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac" -O /usr/local/bin/tbd
          chmod +x /usr/local/bin/tbd 

      - name: Download YTLite .deb 
        run: wget "https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.ytlite_version }}/com.dvntm.ytlite_${{ inputs.ytlite_version }}_iphoneos-arm64.deb" --no-verbose -O ytlite.deb

      - name: Clone Open in YouTube (Safari Extension)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension.git
          cd OpenYouTubeSafariExtension
          git sparse-checkout set --no-cone OpenYouTubeSafariExtension.appex
          git checkout
          mv *.appex ${{ github.workspace }}

      - name: Clone YouTubeHeader
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git $THEOS/include/YouTubeHeader

      - name: Clone PSHeader
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git $THEOS/include/PSHeader
    
      - name: Clone YTUHD
        run: git clone --quiet --depth=1 https://github.com/Tonwalter888/YTUHD.git
           
      - name: Clone Return-YouTube-Dislikes
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git

      - name: Clone YouGroupSettings
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git
           
      - name: Clone YTVideoOverlay
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoOverlay.git
          
      - name: Clone YTABConfig
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git
                  
      - name: Clone YouQuality
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouQuality.git

      - name: Clone YouSpeed
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouSpeed.git

      - name: Clone YouMute
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouMute.git

      - name: Clone YouLoop
        run: git clone --quiet --depth=1 https://github.com/Tonwalter888/YouLoop.git

      - name: Clone Alderis
        run: git clone --quiet --depth=1 https://github.com/hbang/Alderis.git

      - name: Clone YouSlider
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouSlider.git

      - name: Clone YTSilentVote
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YTSilentVote.git

      - name: Clone YouShare
        run: git clone --quiet --depth=1 https://github.com/Tonwalter888/YouShare.git

      - name: Clone Gonerino
        run: git clone --quiet --depth=1 https://github.com/castdrian/Gonerino.git

      - name: Clone YTweaks
        run: git clone --quiet --depth=1 https://github.com/fosterbarnes/YTweaks.git

      - name: Clone YouGetCaption
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouGetCaption.git

      - name: Clone YTFlags
        run: git clone --quiet --depth=1 https://github.com/Tonwalter888/YTFlags.git
        
      - name: Build YTUHD
        run: |
          cd YTUHD
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytuhd.deb

      - name: Build Return-YouTube-Dislikes
        run: |
          cd Return-YouTube-Dislikes
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ryd.deb

      - name: Build YouGroupSettings
        run: |
          cd YouGroupSettings
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ygs.deb

      - name: Build YTVideoOverlay
        run: |
          cd YTVideoOverlay
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytvo.deb

      - name: Build YTABConfig
        run: |
          cd YTABConfig
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytabconfig.deb

      - name: Build YouQuality
        run: |
          cd YouQuality
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youquality.deb

      - name: Build YouSpeed
        run: |
          cd YouSpeed
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youspeed.deb

      - name: Build YouMute
        run: |
          cd YouMute
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ym.deb 

      - name: Build YouLoop
        run: |
          cd YouLoop
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youloop.deb

      - name: Build YouSlider
        run: |
          cd YouSlider
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youslider.deb

      - name: Build Alderis
        run: |
          cd Alderis
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/alderis.deb

      - name: Build YTSilentVote
        run: |
          cd YTSilentVote
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytnovote.deb  

      - name: Build YouShare
        run: |
          cd YouShare
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youshare.deb
          
      - name: Build Gonerino
        run: |
          cd Gonerino
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/gonerino.deb

      - name: Build YouGetCaption
        run: |
          cd YouGetCaption
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ygc.deb

      - name: Build YTweaks
        run: |
          cd YTweaks
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytweaks.deb
          
      - name: Build YTFlags
        run: |
          cd YTFlags
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytflags.deb
  
      - name: Inject Tweaks Into IPA
        run: |
          tweaks="OpenYouTubeSafariExtension.appex"

          for f in *.deb; do
            if [ -f "$f" ]; then
              tweaks="$tweaks $f"
            fi
          done

          cyan -i youtube.ipa -o YTLitePlusEXTRA_20.21.6_v${{ inputs.ytlite_version }}.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ytliteplusextra-ip7p-ipa${{ github.run_number }}
          name: YTLitePlusEXTRA_20.21.6_v${{ inputs.ytlite_version }} (${{ github.run_number }}) 
          files: YTLitePlusEXTRA_20.21.6_v${{ inputs.ytlite_version }}.ipa
          draft: true

      - name: Job Summary - Build Complete
        run: |
          echo -e '### 🛠️ Build YTLitePlusEXTRA IPA Complete!' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the Draft Release Link
        run: |
          echo -e '### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases' >> $GITHUB_STEP_SUMMARY
     
      - name: Job Summary - Cleanup
        run: |
          echo -e '### 🧹 Cleanup\n\nYou can remove previous GitHub Actions run here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-workflows-run.yml And if you want to delelte old draft releases you have then here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-draft-releases.yml' >> $GITHUB_STEP_SUMMARY
